apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfake-ui
  namespace: deepfake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepfake-ui
  template:
    metadata:
      labels:
        app: deepfake-ui
    spec:
      containers:
        - name: ui
          image: ghcr.io/sunny-debug/cs598:latest
          imagePullPolicy: Always
          workingDir: /app
          command: ["python"]
          args:
            - "-m"
            - "streamlit"
            - "run"
            - "streamlit_app/app.py"
            - "--server.address=0.0.0.0"
            - "--server.port=8501"
            - "--server.headless=true"
          env:
            - name: API_BASE
              value: "http://deepfake-api-svc.deepfake.svc.cluster.local"
            - name: STREAMLIT_RUNTIME_SCRATCH_DIR
              value: "/tmp"
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"