apiVersion: v1
kind: Service
metadata:
  name: deepfake-ui
  namespace: deepfake
  labels:
    app: deepfake-ui
spec:
  type: NodePort
  selector:
    app: deepfake-ui
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30501
